export const styles = {
  mainContainer: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--color-text-light)',
  },
  simulationWrapper: {
    display: 'flex',
    width: 'clamp(800px, 60vw,1200px)',
    marginBottom: 'clamp(10px, 1vw,15px)',
  },
  tableWrapper: {
    flex: 1,
    width: 'clamp(600px, 45vw,810px)',
    height: 'clamp(250px, 40vh,400px)',
    display: 'flex',
    flexDirection: 'column',
  },
  tabSectionContainer: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    height: 'clamp(25px, 4vh, 35px)',
    borderRadius: '10px 10px 0 0',
    borderTop: '1px solid #333',
    borderRight: '1px solid #333',
    borderLeft: '1px solid #333',
    boxSizing: 'border-box',
    alignItems: 'center',
    backgroundColor: 'var(--color-background)',
  },
  tabBarWrapper: {
    display: 'flex',
    flexDirection: 'row',
    flex: 1,
    height: '100%',
    alignItems: 'center',
    paddingLeft: '5px',
    overflow: 'hidden',
  },
  tabBar: {
    display: 'flex',
    flexDirection: 'row',
    height: '100%',
    flex: 1,
    overflow: 'hidden',
    alignItems: 'center',
  },
  tab: {
    padding: 'clamp(2px, 0.3vw,5px) clamp(8px, 0.7vw,10px)',
    cursor: 'pointer',
    marginRight: '1px',
    borderRadius: '5px',
    backgroundColor: 'black',
    borderRight: '1px solid #333',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    flex: '1 1 auto', // Allow tabs to shrink
    minWidth: '60px',
    maxWidth: 'clamp(50px, 5vw, 80px)',
    height: 'clamp(25px, 4vh, 30px)',
    transition: 'background-color 0.2s ease, transform 0.2s ease',
    '&:hover': {
      backgroundColor: '#2b2b2e',
    },
    fontSize: "clamp(9px, 0.8vw,10px)"
  },
  activeTab: {
    
    maxWidth: 'clamp(50px, 5vw, 80px)',
    fontSize: "clamp(9px, 0.8vw,10px)",
    padding: 'clamp(3px, 0.4vw,5px) clamp(9px, 0.8vw,10px)',
    borderTop: '1px solid #444',
    borderLeft: '1px solid #444',
    borderRight: '1px solid #444',
    cursor: 'pointer',
    marginRight: '5px',
    marginLeft: '5px',
    marginTop: '5px',
    backgroundColor: 'var(--color-hover-trans)',
    color: 'white',
    borderRadius: '5px',
    display: 'flex',
    alignItems: 'center',
    flex: '1 1 auto', // Allow active tab to shrink
    minWidth: '60px',
    maxWidth: 'clamp(50px, 5vw, 80px)',
    height: 'clamp(25px, 4vh, 35px)',
    transition: 'background-color 0.2s ease, transform 0.2s ease',
    '&:hover': {
      backgroundColor: '#666',
    },
  },
  tabLabel: {
    flex: '1 1 auto',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  closeTabButton: {
    opacity: 0,
    marginLeft: '5px',
    color: 'red',
    cursor: 'pointer',
    transition: 'opacity 0.1s ease',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  tabCloseButtonOnHover: {
    opacity: 1,
  },
  addTabButton: {
    padding: 'clamp(2px, 0.3vw,5px) clamp(8px, 1.5vw,10px)',
    backgroundColor: 'var(--color-hover-trans)',
    color: 'white',
    border: '1px solid #333',
    borderRadius: '5px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 'clamp(14px, 2vh,15px)',
    marginLeft: '5px',
    marginRight: '5px',
    flexShrink: 0,
    height: 'clamp(25px, 2.7vh, 30px)',
  },
  // ---------------- Add Position -----------------------
  addBarContainer: {
    width: 'clamp(120px,12vw,180px)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'clamp(8px, 1.5vw,10px)',
    padding: 'clamp(8px, 0.5vw,10px)',
    backgroundColor: 'var(--color-hover-trans)',
    borderRadius: '10px',
    border: '1px solid #333',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
    alignItems: 'stretch',
    marginRight: 'clamp(8px, 0.5vw,10px)',
  },
  noDataContainer: {
    textAlign: 'center',
    justifyContent: 'center',
    flex: 1,
    height: '350px',
    width: '100%',
    overflowX: 'auto',
    overflowY: 'auto',
    backgroundColor: 'var(--color-hover-trans)',
    borderRadius: '0 0 10px 10px',
    borderBottom: '1px solid #333',
    borderLeft: '1px solid #333',
    borderRight: '1px solid #333',
    padding: '100px',
    fontSize: '13px',
    color: '#888',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
  },
  inputContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: '4px',
    width: '100%',
  },
  inputLabel: {
    fontSize: 'clamp(0.5rem,0.5vw,0.6rem)',
    color: 'var(--color-text-light)',
    textAlign: 'center',
  },
  numberInput: {
    padding: '8px',
    width: '100%',
    height: 'clamp(25px, 1.4vh, 30px)',
    backgroundColor: 'var(--color-background)',
    color: 'white',
    border: '1px solid #444',
    borderRadius: '5px',
    fontSize: 'clamp(0.6rem,0.6vw,0.7rem)',
    transition: 'border-color 0.2s ease, transform 0.2s ease',
    textAlign: 'center',
  },
  addButton: {
    padding: '7px 10px',
    backgroundColor: 'var(--color-primary)',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: 'clamp(0.6rem,0.6vw,0.7rem)',
    letterSpacing: '0.04rem',
    transition: 'background-color 0.2s ease, transform 0.2s ease',
    width: '100%',
  },
  sideButton: {
    padding: '8px',
    width: '100%',
    height: 'clamp(24px, 1.3vh, 30px)',
    backgroundColor: 'var(--color-background)',
    color: 'var(--color-text-light)',
    border: '1px solid #444',
    borderRadius: '5px',
    fontSize: 'clamp(0.6rem,0.6vw,0.7rem)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-color 0.2s ease',
  },
  mainSimulationContainer: {
    flex: 1,
    height: '350px',
    width: '100%',
    overflowX: 'auto',
    overflowY: 'auto',
    backgroundColor: 'var(--color-hover-trans)',
    borderRadius: '0 0 10px 10px',
    borderBottom: '1px solid #333',
    borderLeft: '1px solid #333',
    borderRight: '1px solid #333',
    padding: '10px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
  },
  tableContainer: {
    width: '100%',
    backgroundColor: 'var(--color-background-bar)',
    borderRadius: '10px',
    borderCollapse: 'separate',
    borderSpacing: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tableRowContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    margin: '0',
    padding: '0',
  },
  tableHeader: {
    width: '100%',
    padding: 'clamp(2px, 0.2vw,7px)',
    fontSize: 'clamp(0.5rem,0.6vw,0.6rem)',
    fontWeight: '600',
    textAlign: 'center',
    backgroundColor: 'var(--color-background-tooltip)',
    color: '#666',
    borderBottom: '1px dashed #444',
    letterSpacing: '0.05rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '8px',
  },
  tableRow: {
    transition: 'background-color 0.2s ease',
  },
  tableCell: {
    width: '100%',
    paddingRight: '4px',
    color: 'var(--color-text-light)',
    fontSize: 'clamp(0.6rem,0.6vw,0.7rem)',
    backgroundColor: 'transparent',
    borderRadius: '10px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    boxSizing: 'border-box',
  },
  noTradesCell: {
    textAlign: 'center',
    padding: '20px',
    color: 'var(--color-text-light)',
    fontSize: 'clamp(0.6rem,0.6vw,0.7rem)',
    backgroundColor: 'var(--color-background-bar)',
  },
  checkbox: {
    cursor: 'pointer',
  },
  cellSelect: {
    width: '100%',
    padding: 'clamp(4px, 0.4vw,6px)',
    backgroundColor: 'var(--color-background)',
    color: 'var(--color-input-text)',
    border: '1px solid #333',
    borderRadius: '6px',
    fontSize: 'clamp(0.6rem,0.6vw,0.7rem)',
    transition: 'border-color 0.2s ease',
    textAlign: 'center',
    display: 'block',
    margin: '0 auto',
  },
  cellInput: {
    width: '100%',
    padding: 'clamp(4px, 0.4vw,6px)',
    backgroundColor: 'var(--color-background)',
    color: 'var(--color-input-text)',
    border: '1px solid #333',
    borderRadius: '6px',
    fontSize: 'clamp(0.6rem,0.6vw,0.7rem)',
    transition: 'border-color 0.2s ease',
    textAlign: 'center',
    display: 'block',
    margin: '0 auto',
  },
  cellButton: {
    padding: 'clamp(4px, 0.4vw,6px) clamp(8px, 0.9vw,12px)',
    backgroundColor: 'var(--color-background)',
    color: 'var(--color-text-light)',
    border: '1px solid #333',
    borderRadius: '6px',
    fontFamily: "'Roboto', sans-serif",
    fontSize: 'clamp(0.6rem,0.6vw,0.7rem)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-color 0.2s ease',
    width: '100%',
    margin: '0 auto',
  },
  deleteIcon: {
    width: 'clamp(8px, 0.8vw,12px)',
    height: 'clamp(10px, 1.1vw,15px)',
    backgroundSize: '60% 60%',
    backgroundRepeat: 'no-repeat',
    cursor: 'pointer',
    display: 'block',
    margin: '0 auto',
  },
  chartContainer: {
    marginTop: 'clamp(10px, 2vh, 20px)',
    width: 'clamp(800px, 60vw,1200px)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'var(--color-background)',
    borderRadius: '10px',
    border: '1px solid var(--color-border)',
    padding: '10px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
  },
};